

export const INTRO_CONTENT = {
  English: {
    sectionTitle: "What you can do with this app",
    feature1Title: "Natural Spoken Expressions",
    feature1Desc: "AI suggests the best casual expressions for the context, such as the difference between 'Iku-yo' and 'Ikimasu'.",
    feature2Title: "Detailed Explanations",
    feature2Desc: "It's not just translation. You can learn the nuances and 'why' behind each expression.",
    card1Title: "Enjoy Anime & Movies more!",
    card1Desc: "Ever felt the subtitles don't match the nuance? Understand the emotions behind every line and phrase.",
    card2Title: "Talk casually with friends!",
    card2Desc: "Graduate from polite Japanese. We support you to speak in 'Tame-guchi' naturally with your close friends.",
    card3Title: "Master Social Media & Messaging!",
    card3Desc: "Translate slang and casual social media phrases perfectly. Learn the real Japanese used by locals today.",
    footerTitle: "From 'Textbook Japanese' to 'Real Japanese for Tomorrow.'",
    footerDesc: "Graduate from just memorizing and jump into real conversations. Whether it's anime lines or daily texts, this app has your back.",
  },
  Japanese: {
    sectionTitle: "このアプリでできること",
    feature1Title: "自然な口語表現",
    feature1Desc: "「行くよ」と「行きます」の違いなど、文脈に合わせた最適なカジュアル表現をAIが提案します。",
    feature2Title: "詳細な解説付き",
    feature2Desc: "単なる翻訳だけでなく、なぜその表現が使われるのか、ニュアンスまでしっかり学べます。",
    card1Title: "アニメや映画がもっと楽しく！",
    card1Desc: "「あれ、字幕とニュアンス違くない？」そんな疑問を解消。キャラの熱いセリフや背景にある感情まで理解できます。",
    card2Title: "友達とタメ口で話したい！",
    card2Desc: "「〜です・ます」は卒業。もっと距離を縮めたい友達や恋人と、自然なリズムで会話ができるようサポートします。",
    card3Title: "SNSやLINEを使いこなす！",
    card3Desc: "流行りのスラングや崩した表現もAIがバッチリ翻訳。今の日本人が実際に使っている言葉が身につきます。",
    footerTitle: "「教科書の日本語」から、「明日使える日本語」へ。",
    footerDesc: "覚えるだけの学習は卒業して、今すぐリアルな会話に飛び込みましょう。アニメもLINEも、このアプリがあれば大丈夫。",
  },
    Korean: {
    sectionTitle: "이 앱으로 할 수 있는 것",
    feature1Title: "자연스러운 구어체 표현",
    feature1Desc: "'이쿠요'와 '이키마스'의 차이 등 문맥에 맞는 최적의 캐주얼 표현을 AI가 제안합니다.",
    feature2Title: "상세한 해설 포함",
    feature2Desc: "단순한 번역이 아니라, 왜 그런 표현을 쓰는지 뉘앙스까지 확실히 배울 수 있습니다.",
    card1Title: "애니메이션과 영화를 더 즐겁게!",
    card1Desc: "「어라, 자막이랑 뉘앙스가 다른데?」 그런 의문을 해소. 캐릭터의 뜨거운 대사와 감정까지 이해할 수 있게 됩니다.",
    card2Title: "친구와 반말로 대화하기!",
    card2Desc: "존댓말은 이제 안녕. 더 친해지고 싶은 친구나 연인과 자연스러운 리듬으로 반말 대화를 할 수 있도록 도와드립니다.",
    card3Title: "SNS와 라인 마스터하기!",
    card3Desc: "유행하는 슬랭이나 SNS 표현도 AI가 완벽 번역. 현재 일본인들이 실제로 사용하는 언어를 익힐 수 있습니다.",
    footerTitle: "「교과서 속 일본어」에서 「내일 당장 쓰는 일본어」로.",
    footerDesc: "암기 위주의 학습은 졸업하고 지금 바로 실제 대화에 뛰어드세요. 애니메이션 대사도 메시지도 이 앱만 있으면 충분합니다.",
  },
    Chinese: {
    sectionTitle: "这个应用能做什么",
    feature1Title: "自然口语表达",
    feature1Desc: "AI 会根据语境建议最佳的休闲表达方式，例如“Iku-yo”和“Ikimasu”之间的微妙区别。",
    feature2Title: "详细的解释说明",
    feature2Desc: "不仅仅是翻译，您还能深入学习每种表达方式背后的原因和语境差异。",
    card1Title: "更快乐地看动漫和电影！",
    card1Desc: "觉得字幕翻译不到位？深入理解台词背后的热血情感和微妙的语气变化。",
    card2Title: "想和朋友用口语交流！",
    card2Desc: "告别死板的敬语。帮助您和想亲近的朋友或恋人，用自然的节奏进行日常口语交流。",
    card3Title: "玩转 SNS 和 LINE！",
    card3Desc: "流行俚语和社交媒体上的缩略表达，AI 都能精准翻译。掌握日本人现在真正使用的语言。",
    footerTitle: "从“教科书日语”迈向“明天就能用的日语”。",
    footerDesc: "告别死记硬背的阶段，立即投入真实的对话吧。无论是动漫名言还是日常聊天，这款应用都能帮到你。",
  }
};