export const PLANS_UI = {
  Japanese: {
    monthlyTitle: "月額プラン",
    monthlySub: "いつでも解約可能",
    annualTitle: "年額プラン",
    annualSub: "2ヶ月分お得！",
    bestValue: "一番お得！",
    monthlyPrice: "$3.99",
    annualPrice: "$39.99",
    perMonth: "実質 $3.33/月",
    proFeatures: "Proプランの特典",
    unlimitedTitle: "翻訳回数が無制限",
    unlimitedDesc: "制限を気にせず、毎日使い放題です",
    comingSoonTitle: "今後のアップデート...",
    comingSoonDesc: "方言・フォーマル翻訳・音声読み上げ・スラング詳細解説など",
    paymentBtn: "プランを確定する",
    selectBtn: "プランを選択してください"
  },
  English: {
    monthlyTitle: "Monthly Plan",
    monthlySub: "Cancel anytime",
    annualTitle: "Annual Plan",
    annualSub: "Get 2 months free",
    bestValue: "Best Value!",
    monthlyPrice: "$3.99",
    annualPrice: "$39.99",
    perMonth: "Only $3.33/month",
    proFeatures: "Pro Benefits",
    unlimitedTitle: "Unlimited Translations",
    unlimitedDesc: "No daily limits, translate as much as you want",
    comingSoonTitle: "Coming Soon...",
    comingSoonDesc: "Dialects, formal Japanese, voice playback, and deep slang insights",
    paymentBtn: "Confirm Payment",
    selectBtn: "Select a plan"
  },
  Korean: {
    monthlyTitle: "월간 플랜",
    monthlySub: "언제든 해지 가능",
    annualTitle: "연간 플랜",
    annualSub: "2개월분 할인 혜택!",
    bestValue: "최고의 선택!",
    monthlyPrice: "$3.99",
    annualPrice: "$39.99",
    perMonth: "실질 월 $3.33",
    proFeatures: "Pro 플랜 혜택",
    unlimitedTitle: "번역 횟수 무제한",
    unlimitedDesc: "횟수 제한 없이 매일 마음껏 사용하세요",
    comingSoonTitle: "업데이트 예정...",
    comingSoonDesc: "방언·격식체 번역·음성 낭독·슬랭 상세 해설 등",
    paymentBtn: "결제하기",
    selectBtn: "플랜을 선택해 주세요"
  },
  Chinese: {
    monthlyTitle: "月度方案",
    monthlySub: "随时可以取消",
    annualTitle: "年度方案",
    annualSub: "节省 2 个月的费用！",
    bestValue: "最划算！",
    monthlyPrice: "$3.99",
    annualPrice: "$39.99",
    perMonth: "每月仅 $3.33",
    proFeatures: "Pro 会员权益",
    unlimitedTitle: "无限次翻译次数",
    unlimitedDesc: "无需担心限制，每天尽情使用",
    comingSoonTitle: "即将推出...",
    comingSoonDesc: "方言、商务日语、语音朗读、流行语深度解析等",
    paymentBtn: "确认支付",
    selectBtn: "请选择方案"
  }
};